/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/kadmila/Abyss-Browser/abyss_core/windll */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "abyss_events.go"


#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "abyst.go"


#include <stdint.h>
#include <windows.h>

#line 1 "cgo-generated-wrapper"

#line 3 "collocatedh3.go"


#include <stdint.h>
#include <windows.h>

#line 1 "cgo-generated-wrapper"

#line 3 "dll.go"


#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "http.go"


#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "world.go"


#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) int Event_WorldEnter_Query(uintptr_t h_event, char* world_session_id_buf, char* url_buf_ptr, int url_buf_len);
extern __declspec(dllexport) int Event_SessionRequest_Query(uintptr_t h_event, char* world_session_id_buf, char* peer_session_id_buf, char* peer_id_buf_ptr, int peer_id_buf_len);
extern __declspec(dllexport) int Event_SessionReady_Query(uintptr_t h_event, char* world_session_id_buf, char* peer_session_id_buf, char* peer_id_buf_ptr, int peer_id_buf_len);
extern __declspec(dllexport) int Event_SessionClose_Query(uintptr_t h_event, char* world_session_id_buf, char* peer_session_id_buf, char* peer_id_buf_ptr, int peer_id_buf_len);
extern __declspec(dllexport) int Event_ObjectAppend_Query(uintptr_t h_event, char* world_session_id_buf, char* peer_session_id_buf, char* peer_id_buf_ptr, int peer_id_buf_len, int* object_count_out);
extern __declspec(dllexport) int Event_ObjectAppend_GetObjects(uintptr_t h_event, char** object_id_bufs, float** object_transform_bufs, char** object_addr_bufs, int object_addr_buf_len);
extern __declspec(dllexport) int Event_ObjectDelete_Query(uintptr_t h_event, char* world_session_id_buf, char* peer_session_id_buf, char* peer_id_buf_ptr, int peer_id_buf_len, int* object_count_out);
extern __declspec(dllexport) int Event_ObjectDelete_GetObjectIDs(uintptr_t h_event, char** object_id_bufs);
extern __declspec(dllexport) int Event_WorldLeave_Query(uintptr_t h_event, char* world_session_id_buf, int* code_out, char* message_buf_ptr, int message_buf_len);
extern __declspec(dllexport) int Event_PeerConnected_Query(uintptr_t h_event, uintptr_t* peer_handle_out, char* peer_id_buf_ptr, int peer_id_buf_len);
extern __declspec(dllexport) void ClosePeer(uintptr_t h_peer);
extern __declspec(dllexport) int Event_PeerDisconnected_Query(uintptr_t h_event, char* peer_id_buf_ptr, int peer_id_buf_len);
extern __declspec(dllexport) uintptr_t AbystClient_Get(uintptr_t h_client, HANDLE h_event, char* peer_id_ptr, int peer_id_len, char* path_ptr, int path_len, uintptr_t* result_handle_out);
extern __declspec(dllexport) uintptr_t AbystClient_Post(uintptr_t h_client, HANDLE h_event, char* peer_id_ptr, int peer_id_len, char* path_ptr, int path_len, char* content_type_ptr, int content_type_len, char* body_ptr, int body_len, uintptr_t* result_handle_out);
extern __declspec(dllexport) uintptr_t AbystClient_Head(uintptr_t h_client, HANDLE h_event, char* peer_id_ptr, int peer_id_len, char* path_ptr, int path_len, uintptr_t* result_handle_out);
extern __declspec(dllexport) uintptr_t Http3Client_Get(uintptr_t h_client, HANDLE h_event, char* url_ptr, int url_len, uintptr_t* result_handle_out);
extern __declspec(dllexport) uintptr_t Http3Client_Post(uintptr_t h_client, HANDLE h_event, char* url_ptr, int url_len, char* content_type_ptr, int content_type_len, char* body_ptr, int body_len, uintptr_t* result_handle_out);
extern __declspec(dllexport) uintptr_t Http3Client_Head(uintptr_t h_client, HANDLE h_event, char* url_ptr, int url_len, uintptr_t* result_handle_out);
extern __declspec(dllexport) int Init();
extern __declspec(dllexport) int GetErrorBodyLength(uintptr_t h_error);
extern __declspec(dllexport) int GetErrorBody(uintptr_t h_error, char* buf_ptr, int buf_len);
extern __declspec(dllexport) void CloseError(uintptr_t h_error);
extern __declspec(dllexport) uintptr_t NewHost(char* root_key_ptr, int root_key_len, uintptr_t* out);
extern __declspec(dllexport) void CloseHost(uintptr_t h);
extern __declspec(dllexport) void Host_Run(uintptr_t h);
extern __declspec(dllexport) uintptr_t Host_WaitForEvent(uintptr_t h, int* event_type_out, uintptr_t* event_handle_out);
extern __declspec(dllexport) void CloseEvent(uintptr_t h);
extern __declspec(dllexport) uintptr_t Host_OpenWorld(uintptr_t h, char* world_url_ptr, int world_url_len, uintptr_t* world_handle_out);
extern __declspec(dllexport) uintptr_t Host_JoinWorld(uintptr_t h, uintptr_t h_peer, char* path_ptr, int path_len, uintptr_t* world_handle_out);
extern __declspec(dllexport) void CloseWorld(uintptr_t h_world);
extern __declspec(dllexport) uintptr_t Host_ExposeWorldForJoin(uintptr_t h, uintptr_t h_world, char* path_ptr, int path_len);
extern __declspec(dllexport) void Host_HideWorld(uintptr_t h, uintptr_t h_world);
extern __declspec(dllexport) int Host_LocalAddrCandidates(uintptr_t h, char* buf_ptr, int buf_len);
extern __declspec(dllexport) int Host_ID(uintptr_t h, char* buf_ptr, int buf_len);
extern __declspec(dllexport) int Host_RootCertificate(uintptr_t h, char* buf_ptr, int buf_len);
extern __declspec(dllexport) int Host_HandshakeKeyCertificate(uintptr_t h, char* buf_ptr, int buf_len);
extern __declspec(dllexport) uintptr_t Host_AppendKnownPeer(uintptr_t h, char* root_cert_ptr, int root_cert_len, char* handshake_info_cert_ptr, int handshake_info_cert_len);
extern __declspec(dllexport) uintptr_t Host_EraseKnownPeer(uintptr_t h, char* id_ptr, int id_len);
extern __declspec(dllexport) uintptr_t Host_Dial(uintptr_t h, char* id_ptr, int id_len);
extern __declspec(dllexport) uintptr_t Host_ConfigAbystGateway(uintptr_t h, char* config_ptr, int config_len);
extern __declspec(dllexport) uintptr_t Host_NewAbystClient(uintptr_t h);
extern __declspec(dllexport) void CloseAbyssClient(uintptr_t h);
extern __declspec(dllexport) uintptr_t Host_NewCollocatedHttp3Client(uintptr_t h);
extern __declspec(dllexport) void CloseAbyssClientCollocatedHttp3Client(uintptr_t h);
extern __declspec(dllexport) void CloseHttpIOResult(uintptr_t h_result);
extern __declspec(dllexport) uintptr_t HttpIOResult_Unpack(uintptr_t h_result, uintptr_t* response_handle_out);
extern __declspec(dllexport) int HttpResponse_StatusCode(uintptr_t h_response);
extern __declspec(dllexport) int HttpResponse_GetHeader(uintptr_t h_response, char* key_ptr, int key_len, char* value_buf_ptr, int value_buf_len);
extern __declspec(dllexport) int HttpResponse_GetAllHeaders(uintptr_t h_response, char* buf_ptr, int buf_len);
extern __declspec(dllexport) int HttpResponse_ReadBody(uintptr_t h_response, char* buf_ptr, int buf_len);
extern __declspec(dllexport) void CloseHttpResponse(uintptr_t h_response);
extern __declspec(dllexport) void World_AcceptSession(uintptr_t h_host, uintptr_t h_world, uintptr_t h_peer, char* peer_session_id_buf);
extern __declspec(dllexport) void World_DeclineSession(uintptr_t h_host, uintptr_t h_world, uintptr_t h_peer, char* peer_session_id_buf, int code, char* message_buf_ptr, int message_buf_len);
extern __declspec(dllexport) void World_Close(uintptr_t h_host, uintptr_t h_world);
extern __declspec(dllexport) void World_ObjectAppend(uintptr_t h_host, uintptr_t h_world, int peer_count, uintptr_t* h_peers, char** peer_session_id_bufs, int object_count, char** object_id_bufs, float** object_transform_bufs, char** object_addr_bufs, int object_addr_buf_len);
extern __declspec(dllexport) void World_ObjectDelete(uintptr_t h_host, uintptr_t h_world, int peer_count, uintptr_t* h_peers, char** peer_session_id_bufs, int object_count, char** object_id_bufs);

#ifdef __cplusplus
}
#endif
