// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediaType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from mediaType.proto</summary>
public static partial class MediaTypeReflection {

  #region Descriptor
  /// <summary>File descriptor for mediaType.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MediaTypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9tZWRpYVR5cGUucHJvdG8qGAoJTWVkaWFUeXBlEgsKB1RleHR1cmUQAGIG",
          "cHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MediaType), }, null, null));
  }
  #endregion

}
#region Enums
public enum MediaType {
  [pbr::OriginalName("Texture")] Texture = 0,
}

#endregion


#endregion Designer generated code
