// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResourceRole.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ResourceRole.proto</summary>
public static partial class ResourceRoleReflection {

  #region Descriptor
  /// <summary>File descriptor for ResourceRole.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ResourceRoleReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJSZXNvdXJjZVJvbGUucHJvdG8qdQoMUmVzb3VyY2VSb2xlEggKBE1lc2gQ",
          "ABIKCgZBbGJlZG8QARIKCgZOb3JtYWwQAhINCglSb3VnaG5lc3MQAxILCgdN",
          "ZXRhbGljEAQSDAoIU3BlY3VsYXIQBRILCgdPcGFjaXR5EAYSDAoIRW1pc3Np",
          "b24QByowCgpFbGVtZW50VGFnEgUKAU8QABIHCgNPYmoQARIICgRQYnJtEAIS",
          "CAoEQmNvbBADKikKCVZhbHVlUm9sZRIICgREaW1BEAASCAoERGltQhABEggK",
          "BERpbUMQAmIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ResourceRole), typeof(global::ElementTag), typeof(global::ValueRole), }, null, null));
  }
  #endregion

}
#region Enums
public enum ResourceRole {
  [pbr::OriginalName("Mesh")] Mesh = 0,
  [pbr::OriginalName("Albedo")] Albedo = 1,
  [pbr::OriginalName("Normal")] Normal = 2,
  [pbr::OriginalName("Roughness")] Roughness = 3,
  [pbr::OriginalName("Metalic")] Metalic = 4,
  [pbr::OriginalName("Specular")] Specular = 5,
  [pbr::OriginalName("Opacity")] Opacity = 6,
  [pbr::OriginalName("Emission")] Emission = 7,
}

public enum ElementTag {
  [pbr::OriginalName("O")] O = 0,
  [pbr::OriginalName("Obj")] Obj = 1,
  [pbr::OriginalName("Pbrm")] Pbrm = 2,
  [pbr::OriginalName("Bcol")] Bcol = 3,
}

public enum ValueRole {
  [pbr::OriginalName("DimA")] DimA = 0,
  [pbr::OriginalName("DimB")] DimB = 1,
  [pbr::OriginalName("DimC")] DimC = 2,
}

#endregion


#endregion Designer generated code
