// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UIAction.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AbyssCLI.ABI {

  /// <summary>Holder for reflection information generated from UIAction.proto</summary>
  public static partial class UIActionReflection {

    #region Descriptor
    /// <summary>File descriptor for UIAction.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UIActionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5VSUFjdGlvbi5wcm90bxoQY29tbW9udHlwZS5wcm90byLlBAoIVUlBY3Rp",
            "b24SHgoEaW5pdBgBIAEoCzIOLlVJQWN0aW9uLkluaXRIABIeCgRraWxsGAIg",
            "ASgLMg4uVUlBY3Rpb24uS2lsbEgAEikKCm1vdmVfd29ybGQYAyABKAsyEy5V",
            "SUFjdGlvbi5Nb3ZlV29ybGRIABIvCg1zaGFyZV9jb250ZW50GAQgASgLMhYu",
            "VUlBY3Rpb24uU2hhcmVDb250ZW50SAASMwoPdW5zaGFyZV9jb250ZW50GAUg",
            "ASgLMhguVUlBY3Rpb24uVW5zaGFyZUNvbnRlbnRIABItCgxjb25uZWN0X3Bl",
            "ZXIYCiABKAsyFS5VSUFjdGlvbi5Db25uZWN0UGVlckgAEjAKDWNvbnNvbGVf",
            "aW5wdXQY5wcgASgLMhYuVUlBY3Rpb24uQ29uc29sZUlucHV0SAAaJgoESW5p",
            "dBIQCghyb290X2tleRgBIAEoDBIMCgRuYW1lGAIgASgJGhQKBEtpbGwSDAoE",
            "Y29kZRgBIAEoBRoeCglNb3ZlV29ybGQSEQoJd29ybGRfdXJsGAEgASgJGlEK",
            "DFNoYXJlQ29udGVudBIMCgR1dWlkGAEgASgMEgsKA3VybBgCIAEoCRISCgNw",
            "b3MYAyABKAsyBS5WZWMzEhIKA3JvdBgEIAEoCzIFLlZlYzQaHgoOVW5zaGFy",
            "ZUNvbnRlbnQSDAoEdXVpZBgBIAEoDBobCgtDb25uZWN0UGVlchIMCgRhdXJs",
            "GAEgASgJGjAKDENvbnNvbGVJbnB1dBISCgplbGVtZW50X2lkGAEgASgFEgwK",
            "BHRleHQYAiABKAlCBwoFaW5uZXJCD6oCDEFieXNzQ0xJLkFCSWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AbyssCLI.ABI.CommontypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.UIAction), global::AbyssCLI.ABI.UIAction.Parser, new[]{ "Init", "Kill", "MoveWorld", "ShareContent", "UnshareContent", "ConnectPeer", "ConsoleInput" }, new[]{ "Inner" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.UIAction.Types.Init), global::AbyssCLI.ABI.UIAction.Types.Init.Parser, new[]{ "RootKey", "Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.UIAction.Types.Kill), global::AbyssCLI.ABI.UIAction.Types.Kill.Parser, new[]{ "Code" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.UIAction.Types.MoveWorld), global::AbyssCLI.ABI.UIAction.Types.MoveWorld.Parser, new[]{ "WorldUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.UIAction.Types.ShareContent), global::AbyssCLI.ABI.UIAction.Types.ShareContent.Parser, new[]{ "Uuid", "Url", "Pos", "Rot" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.UIAction.Types.UnshareContent), global::AbyssCLI.ABI.UIAction.Types.UnshareContent.Parser, new[]{ "Uuid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.UIAction.Types.ConnectPeer), global::AbyssCLI.ABI.UIAction.Types.ConnectPeer.Parser, new[]{ "Aurl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AbyssCLI.ABI.UIAction.Types.ConsoleInput), global::AbyssCLI.ABI.UIAction.Types.ConsoleInput.Parser, new[]{ "ElementId", "Text" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UIAction : pb::IMessage<UIAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UIAction> _parser = new pb::MessageParser<UIAction>(() => new UIAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UIAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AbyssCLI.ABI.UIActionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UIAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UIAction(UIAction other) : this() {
      switch (other.InnerCase) {
        case InnerOneofCase.Init:
          Init = other.Init.Clone();
          break;
        case InnerOneofCase.Kill:
          Kill = other.Kill.Clone();
          break;
        case InnerOneofCase.MoveWorld:
          MoveWorld = other.MoveWorld.Clone();
          break;
        case InnerOneofCase.ShareContent:
          ShareContent = other.ShareContent.Clone();
          break;
        case InnerOneofCase.UnshareContent:
          UnshareContent = other.UnshareContent.Clone();
          break;
        case InnerOneofCase.ConnectPeer:
          ConnectPeer = other.ConnectPeer.Clone();
          break;
        case InnerOneofCase.ConsoleInput:
          ConsoleInput = other.ConsoleInput.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UIAction Clone() {
      return new UIAction(this);
    }

    /// <summary>Field number for the "init" field.</summary>
    public const int InitFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.UIAction.Types.Init Init {
      get { return innerCase_ == InnerOneofCase.Init ? (global::AbyssCLI.ABI.UIAction.Types.Init) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.Init;
      }
    }

    /// <summary>Field number for the "kill" field.</summary>
    public const int KillFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.UIAction.Types.Kill Kill {
      get { return innerCase_ == InnerOneofCase.Kill ? (global::AbyssCLI.ABI.UIAction.Types.Kill) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.Kill;
      }
    }

    /// <summary>Field number for the "move_world" field.</summary>
    public const int MoveWorldFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.UIAction.Types.MoveWorld MoveWorld {
      get { return innerCase_ == InnerOneofCase.MoveWorld ? (global::AbyssCLI.ABI.UIAction.Types.MoveWorld) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.MoveWorld;
      }
    }

    /// <summary>Field number for the "share_content" field.</summary>
    public const int ShareContentFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.UIAction.Types.ShareContent ShareContent {
      get { return innerCase_ == InnerOneofCase.ShareContent ? (global::AbyssCLI.ABI.UIAction.Types.ShareContent) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.ShareContent;
      }
    }

    /// <summary>Field number for the "unshare_content" field.</summary>
    public const int UnshareContentFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.UIAction.Types.UnshareContent UnshareContent {
      get { return innerCase_ == InnerOneofCase.UnshareContent ? (global::AbyssCLI.ABI.UIAction.Types.UnshareContent) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.UnshareContent;
      }
    }

    /// <summary>Field number for the "connect_peer" field.</summary>
    public const int ConnectPeerFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.UIAction.Types.ConnectPeer ConnectPeer {
      get { return innerCase_ == InnerOneofCase.ConnectPeer ? (global::AbyssCLI.ABI.UIAction.Types.ConnectPeer) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.ConnectPeer;
      }
    }

    /// <summary>Field number for the "console_input" field.</summary>
    public const int ConsoleInputFieldNumber = 999;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AbyssCLI.ABI.UIAction.Types.ConsoleInput ConsoleInput {
      get { return innerCase_ == InnerOneofCase.ConsoleInput ? (global::AbyssCLI.ABI.UIAction.Types.ConsoleInput) inner_ : null; }
      set {
        inner_ = value;
        innerCase_ = value == null ? InnerOneofCase.None : InnerOneofCase.ConsoleInput;
      }
    }

    private object inner_;
    /// <summary>Enum of possible cases for the "inner" oneof.</summary>
    public enum InnerOneofCase {
      None = 0,
      Init = 1,
      Kill = 2,
      MoveWorld = 3,
      ShareContent = 4,
      UnshareContent = 5,
      ConnectPeer = 10,
      ConsoleInput = 999,
    }
    private InnerOneofCase innerCase_ = InnerOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InnerOneofCase InnerCase {
      get { return innerCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInner() {
      innerCase_ = InnerOneofCase.None;
      inner_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UIAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UIAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Init, other.Init)) return false;
      if (!object.Equals(Kill, other.Kill)) return false;
      if (!object.Equals(MoveWorld, other.MoveWorld)) return false;
      if (!object.Equals(ShareContent, other.ShareContent)) return false;
      if (!object.Equals(UnshareContent, other.UnshareContent)) return false;
      if (!object.Equals(ConnectPeer, other.ConnectPeer)) return false;
      if (!object.Equals(ConsoleInput, other.ConsoleInput)) return false;
      if (InnerCase != other.InnerCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (innerCase_ == InnerOneofCase.Init) hash ^= Init.GetHashCode();
      if (innerCase_ == InnerOneofCase.Kill) hash ^= Kill.GetHashCode();
      if (innerCase_ == InnerOneofCase.MoveWorld) hash ^= MoveWorld.GetHashCode();
      if (innerCase_ == InnerOneofCase.ShareContent) hash ^= ShareContent.GetHashCode();
      if (innerCase_ == InnerOneofCase.UnshareContent) hash ^= UnshareContent.GetHashCode();
      if (innerCase_ == InnerOneofCase.ConnectPeer) hash ^= ConnectPeer.GetHashCode();
      if (innerCase_ == InnerOneofCase.ConsoleInput) hash ^= ConsoleInput.GetHashCode();
      hash ^= (int) innerCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (innerCase_ == InnerOneofCase.Init) {
        output.WriteRawTag(10);
        output.WriteMessage(Init);
      }
      if (innerCase_ == InnerOneofCase.Kill) {
        output.WriteRawTag(18);
        output.WriteMessage(Kill);
      }
      if (innerCase_ == InnerOneofCase.MoveWorld) {
        output.WriteRawTag(26);
        output.WriteMessage(MoveWorld);
      }
      if (innerCase_ == InnerOneofCase.ShareContent) {
        output.WriteRawTag(34);
        output.WriteMessage(ShareContent);
      }
      if (innerCase_ == InnerOneofCase.UnshareContent) {
        output.WriteRawTag(42);
        output.WriteMessage(UnshareContent);
      }
      if (innerCase_ == InnerOneofCase.ConnectPeer) {
        output.WriteRawTag(82);
        output.WriteMessage(ConnectPeer);
      }
      if (innerCase_ == InnerOneofCase.ConsoleInput) {
        output.WriteRawTag(186, 62);
        output.WriteMessage(ConsoleInput);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (innerCase_ == InnerOneofCase.Init) {
        output.WriteRawTag(10);
        output.WriteMessage(Init);
      }
      if (innerCase_ == InnerOneofCase.Kill) {
        output.WriteRawTag(18);
        output.WriteMessage(Kill);
      }
      if (innerCase_ == InnerOneofCase.MoveWorld) {
        output.WriteRawTag(26);
        output.WriteMessage(MoveWorld);
      }
      if (innerCase_ == InnerOneofCase.ShareContent) {
        output.WriteRawTag(34);
        output.WriteMessage(ShareContent);
      }
      if (innerCase_ == InnerOneofCase.UnshareContent) {
        output.WriteRawTag(42);
        output.WriteMessage(UnshareContent);
      }
      if (innerCase_ == InnerOneofCase.ConnectPeer) {
        output.WriteRawTag(82);
        output.WriteMessage(ConnectPeer);
      }
      if (innerCase_ == InnerOneofCase.ConsoleInput) {
        output.WriteRawTag(186, 62);
        output.WriteMessage(ConsoleInput);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (innerCase_ == InnerOneofCase.Init) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Init);
      }
      if (innerCase_ == InnerOneofCase.Kill) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Kill);
      }
      if (innerCase_ == InnerOneofCase.MoveWorld) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MoveWorld);
      }
      if (innerCase_ == InnerOneofCase.ShareContent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShareContent);
      }
      if (innerCase_ == InnerOneofCase.UnshareContent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnshareContent);
      }
      if (innerCase_ == InnerOneofCase.ConnectPeer) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConnectPeer);
      }
      if (innerCase_ == InnerOneofCase.ConsoleInput) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ConsoleInput);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UIAction other) {
      if (other == null) {
        return;
      }
      switch (other.InnerCase) {
        case InnerOneofCase.Init:
          if (Init == null) {
            Init = new global::AbyssCLI.ABI.UIAction.Types.Init();
          }
          Init.MergeFrom(other.Init);
          break;
        case InnerOneofCase.Kill:
          if (Kill == null) {
            Kill = new global::AbyssCLI.ABI.UIAction.Types.Kill();
          }
          Kill.MergeFrom(other.Kill);
          break;
        case InnerOneofCase.MoveWorld:
          if (MoveWorld == null) {
            MoveWorld = new global::AbyssCLI.ABI.UIAction.Types.MoveWorld();
          }
          MoveWorld.MergeFrom(other.MoveWorld);
          break;
        case InnerOneofCase.ShareContent:
          if (ShareContent == null) {
            ShareContent = new global::AbyssCLI.ABI.UIAction.Types.ShareContent();
          }
          ShareContent.MergeFrom(other.ShareContent);
          break;
        case InnerOneofCase.UnshareContent:
          if (UnshareContent == null) {
            UnshareContent = new global::AbyssCLI.ABI.UIAction.Types.UnshareContent();
          }
          UnshareContent.MergeFrom(other.UnshareContent);
          break;
        case InnerOneofCase.ConnectPeer:
          if (ConnectPeer == null) {
            ConnectPeer = new global::AbyssCLI.ABI.UIAction.Types.ConnectPeer();
          }
          ConnectPeer.MergeFrom(other.ConnectPeer);
          break;
        case InnerOneofCase.ConsoleInput:
          if (ConsoleInput == null) {
            ConsoleInput = new global::AbyssCLI.ABI.UIAction.Types.ConsoleInput();
          }
          ConsoleInput.MergeFrom(other.ConsoleInput);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::AbyssCLI.ABI.UIAction.Types.Init subBuilder = new global::AbyssCLI.ABI.UIAction.Types.Init();
            if (innerCase_ == InnerOneofCase.Init) {
              subBuilder.MergeFrom(Init);
            }
            input.ReadMessage(subBuilder);
            Init = subBuilder;
            break;
          }
          case 18: {
            global::AbyssCLI.ABI.UIAction.Types.Kill subBuilder = new global::AbyssCLI.ABI.UIAction.Types.Kill();
            if (innerCase_ == InnerOneofCase.Kill) {
              subBuilder.MergeFrom(Kill);
            }
            input.ReadMessage(subBuilder);
            Kill = subBuilder;
            break;
          }
          case 26: {
            global::AbyssCLI.ABI.UIAction.Types.MoveWorld subBuilder = new global::AbyssCLI.ABI.UIAction.Types.MoveWorld();
            if (innerCase_ == InnerOneofCase.MoveWorld) {
              subBuilder.MergeFrom(MoveWorld);
            }
            input.ReadMessage(subBuilder);
            MoveWorld = subBuilder;
            break;
          }
          case 34: {
            global::AbyssCLI.ABI.UIAction.Types.ShareContent subBuilder = new global::AbyssCLI.ABI.UIAction.Types.ShareContent();
            if (innerCase_ == InnerOneofCase.ShareContent) {
              subBuilder.MergeFrom(ShareContent);
            }
            input.ReadMessage(subBuilder);
            ShareContent = subBuilder;
            break;
          }
          case 42: {
            global::AbyssCLI.ABI.UIAction.Types.UnshareContent subBuilder = new global::AbyssCLI.ABI.UIAction.Types.UnshareContent();
            if (innerCase_ == InnerOneofCase.UnshareContent) {
              subBuilder.MergeFrom(UnshareContent);
            }
            input.ReadMessage(subBuilder);
            UnshareContent = subBuilder;
            break;
          }
          case 82: {
            global::AbyssCLI.ABI.UIAction.Types.ConnectPeer subBuilder = new global::AbyssCLI.ABI.UIAction.Types.ConnectPeer();
            if (innerCase_ == InnerOneofCase.ConnectPeer) {
              subBuilder.MergeFrom(ConnectPeer);
            }
            input.ReadMessage(subBuilder);
            ConnectPeer = subBuilder;
            break;
          }
          case 7994: {
            global::AbyssCLI.ABI.UIAction.Types.ConsoleInput subBuilder = new global::AbyssCLI.ABI.UIAction.Types.ConsoleInput();
            if (innerCase_ == InnerOneofCase.ConsoleInput) {
              subBuilder.MergeFrom(ConsoleInput);
            }
            input.ReadMessage(subBuilder);
            ConsoleInput = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::AbyssCLI.ABI.UIAction.Types.Init subBuilder = new global::AbyssCLI.ABI.UIAction.Types.Init();
            if (innerCase_ == InnerOneofCase.Init) {
              subBuilder.MergeFrom(Init);
            }
            input.ReadMessage(subBuilder);
            Init = subBuilder;
            break;
          }
          case 18: {
            global::AbyssCLI.ABI.UIAction.Types.Kill subBuilder = new global::AbyssCLI.ABI.UIAction.Types.Kill();
            if (innerCase_ == InnerOneofCase.Kill) {
              subBuilder.MergeFrom(Kill);
            }
            input.ReadMessage(subBuilder);
            Kill = subBuilder;
            break;
          }
          case 26: {
            global::AbyssCLI.ABI.UIAction.Types.MoveWorld subBuilder = new global::AbyssCLI.ABI.UIAction.Types.MoveWorld();
            if (innerCase_ == InnerOneofCase.MoveWorld) {
              subBuilder.MergeFrom(MoveWorld);
            }
            input.ReadMessage(subBuilder);
            MoveWorld = subBuilder;
            break;
          }
          case 34: {
            global::AbyssCLI.ABI.UIAction.Types.ShareContent subBuilder = new global::AbyssCLI.ABI.UIAction.Types.ShareContent();
            if (innerCase_ == InnerOneofCase.ShareContent) {
              subBuilder.MergeFrom(ShareContent);
            }
            input.ReadMessage(subBuilder);
            ShareContent = subBuilder;
            break;
          }
          case 42: {
            global::AbyssCLI.ABI.UIAction.Types.UnshareContent subBuilder = new global::AbyssCLI.ABI.UIAction.Types.UnshareContent();
            if (innerCase_ == InnerOneofCase.UnshareContent) {
              subBuilder.MergeFrom(UnshareContent);
            }
            input.ReadMessage(subBuilder);
            UnshareContent = subBuilder;
            break;
          }
          case 82: {
            global::AbyssCLI.ABI.UIAction.Types.ConnectPeer subBuilder = new global::AbyssCLI.ABI.UIAction.Types.ConnectPeer();
            if (innerCase_ == InnerOneofCase.ConnectPeer) {
              subBuilder.MergeFrom(ConnectPeer);
            }
            input.ReadMessage(subBuilder);
            ConnectPeer = subBuilder;
            break;
          }
          case 7994: {
            global::AbyssCLI.ABI.UIAction.Types.ConsoleInput subBuilder = new global::AbyssCLI.ABI.UIAction.Types.ConsoleInput();
            if (innerCase_ == InnerOneofCase.ConsoleInput) {
              subBuilder.MergeFrom(ConsoleInput);
            }
            input.ReadMessage(subBuilder);
            ConsoleInput = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the UIAction message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Init : pb::IMessage<Init>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Init> _parser = new pb::MessageParser<Init>(() => new Init());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Init> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.UIAction.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Init() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Init(Init other) : this() {
          rootKey_ = other.rootKey_;
          name_ = other.name_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Init Clone() {
          return new Init(this);
        }

        /// <summary>Field number for the "root_key" field.</summary>
        public const int RootKeyFieldNumber = 1;
        private pb::ByteString rootKey_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString RootKey {
          get { return rootKey_; }
          set {
            rootKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 2;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Init);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Init other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (RootKey != other.RootKey) return false;
          if (Name != other.Name) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (RootKey.Length != 0) hash ^= RootKey.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (RootKey.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(RootKey);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Name);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (RootKey.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(RootKey);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Name);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (RootKey.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(RootKey);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Init other) {
          if (other == null) {
            return;
          }
          if (other.RootKey.Length != 0) {
            RootKey = other.RootKey;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                RootKey = input.ReadBytes();
                break;
              }
              case 18: {
                Name = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                RootKey = input.ReadBytes();
                break;
              }
              case 18: {
                Name = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Kill : pb::IMessage<Kill>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Kill> _parser = new pb::MessageParser<Kill>(() => new Kill());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Kill> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.UIAction.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Kill() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Kill(Kill other) : this() {
          code_ = other.code_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Kill Clone() {
          return new Kill(this);
        }

        /// <summary>Field number for the "code" field.</summary>
        public const int CodeFieldNumber = 1;
        private int code_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Code {
          get { return code_; }
          set {
            code_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Kill);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Kill other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Code != other.Code) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Code != 0) hash ^= Code.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Code != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Code);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Code != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Code);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Code != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Kill other) {
          if (other == null) {
            return;
          }
          if (other.Code != 0) {
            Code = other.Code;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Code = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Code = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class MoveWorld : pb::IMessage<MoveWorld>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<MoveWorld> _parser = new pb::MessageParser<MoveWorld>(() => new MoveWorld());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<MoveWorld> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.UIAction.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MoveWorld() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MoveWorld(MoveWorld other) : this() {
          worldUrl_ = other.worldUrl_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MoveWorld Clone() {
          return new MoveWorld(this);
        }

        /// <summary>Field number for the "world_url" field.</summary>
        public const int WorldUrlFieldNumber = 1;
        private string worldUrl_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string WorldUrl {
          get { return worldUrl_; }
          set {
            worldUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as MoveWorld);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(MoveWorld other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (WorldUrl != other.WorldUrl) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (WorldUrl.Length != 0) hash ^= WorldUrl.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (WorldUrl.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(WorldUrl);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (WorldUrl.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(WorldUrl);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (WorldUrl.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(WorldUrl);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(MoveWorld other) {
          if (other == null) {
            return;
          }
          if (other.WorldUrl.Length != 0) {
            WorldUrl = other.WorldUrl;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                WorldUrl = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                WorldUrl = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Address Bar Input
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class ShareContent : pb::IMessage<ShareContent>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ShareContent> _parser = new pb::MessageParser<ShareContent>(() => new ShareContent());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ShareContent> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.UIAction.Descriptor.NestedTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ShareContent() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ShareContent(ShareContent other) : this() {
          uuid_ = other.uuid_;
          url_ = other.url_;
          pos_ = other.pos_ != null ? other.pos_.Clone() : null;
          rot_ = other.rot_ != null ? other.rot_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ShareContent Clone() {
          return new ShareContent(this);
        }

        /// <summary>Field number for the "uuid" field.</summary>
        public const int UuidFieldNumber = 1;
        private pb::ByteString uuid_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Uuid {
          get { return uuid_; }
          set {
            uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "url" field.</summary>
        public const int UrlFieldNumber = 2;
        private string url_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Url {
          get { return url_; }
          set {
            url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "pos" field.</summary>
        public const int PosFieldNumber = 3;
        private global::AbyssCLI.ABI.Vec3 pos_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::AbyssCLI.ABI.Vec3 Pos {
          get { return pos_; }
          set {
            pos_ = value;
          }
        }

        /// <summary>Field number for the "rot" field.</summary>
        public const int RotFieldNumber = 4;
        private global::AbyssCLI.ABI.Vec4 rot_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::AbyssCLI.ABI.Vec4 Rot {
          get { return rot_; }
          set {
            rot_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ShareContent);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ShareContent other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Uuid != other.Uuid) return false;
          if (Url != other.Url) return false;
          if (!object.Equals(Pos, other.Pos)) return false;
          if (!object.Equals(Rot, other.Rot)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
          if (Url.Length != 0) hash ^= Url.GetHashCode();
          if (pos_ != null) hash ^= Pos.GetHashCode();
          if (rot_ != null) hash ^= Rot.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Uuid.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Uuid);
          }
          if (Url.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Url);
          }
          if (pos_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Pos);
          }
          if (rot_ != null) {
            output.WriteRawTag(34);
            output.WriteMessage(Rot);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Uuid.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Uuid);
          }
          if (Url.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Url);
          }
          if (pos_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Pos);
          }
          if (rot_ != null) {
            output.WriteRawTag(34);
            output.WriteMessage(Rot);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Uuid.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Uuid);
          }
          if (Url.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
          }
          if (pos_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
          }
          if (rot_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rot);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ShareContent other) {
          if (other == null) {
            return;
          }
          if (other.Uuid.Length != 0) {
            Uuid = other.Uuid;
          }
          if (other.Url.Length != 0) {
            Url = other.Url;
          }
          if (other.pos_ != null) {
            if (pos_ == null) {
              Pos = new global::AbyssCLI.ABI.Vec3();
            }
            Pos.MergeFrom(other.Pos);
          }
          if (other.rot_ != null) {
            if (rot_ == null) {
              Rot = new global::AbyssCLI.ABI.Vec4();
            }
            Rot.MergeFrom(other.Rot);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Uuid = input.ReadBytes();
                break;
              }
              case 18: {
                Url = input.ReadString();
                break;
              }
              case 26: {
                if (pos_ == null) {
                  Pos = new global::AbyssCLI.ABI.Vec3();
                }
                input.ReadMessage(Pos);
                break;
              }
              case 34: {
                if (rot_ == null) {
                  Rot = new global::AbyssCLI.ABI.Vec4();
                }
                input.ReadMessage(Rot);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Uuid = input.ReadBytes();
                break;
              }
              case 18: {
                Url = input.ReadString();
                break;
              }
              case 26: {
                if (pos_ == null) {
                  Pos = new global::AbyssCLI.ABI.Vec3();
                }
                input.ReadMessage(Pos);
                break;
              }
              case 34: {
                if (rot_ == null) {
                  Rot = new global::AbyssCLI.ABI.Vec4();
                }
                input.ReadMessage(Rot);
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class UnshareContent : pb::IMessage<UnshareContent>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<UnshareContent> _parser = new pb::MessageParser<UnshareContent>(() => new UnshareContent());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<UnshareContent> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.UIAction.Descriptor.NestedTypes[4]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UnshareContent() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UnshareContent(UnshareContent other) : this() {
          uuid_ = other.uuid_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UnshareContent Clone() {
          return new UnshareContent(this);
        }

        /// <summary>Field number for the "uuid" field.</summary>
        public const int UuidFieldNumber = 1;
        private pb::ByteString uuid_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Uuid {
          get { return uuid_; }
          set {
            uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as UnshareContent);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(UnshareContent other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Uuid != other.Uuid) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Uuid.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Uuid);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Uuid.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Uuid);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Uuid.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Uuid);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(UnshareContent other) {
          if (other == null) {
            return;
          }
          if (other.Uuid.Length != 0) {
            Uuid = other.Uuid;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Uuid = input.ReadBytes();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Uuid = input.ReadBytes();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class ConnectPeer : pb::IMessage<ConnectPeer>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ConnectPeer> _parser = new pb::MessageParser<ConnectPeer>(() => new ConnectPeer());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ConnectPeer> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.UIAction.Descriptor.NestedTypes[5]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ConnectPeer() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ConnectPeer(ConnectPeer other) : this() {
          aurl_ = other.aurl_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ConnectPeer Clone() {
          return new ConnectPeer(this);
        }

        /// <summary>Field number for the "aurl" field.</summary>
        public const int AurlFieldNumber = 1;
        private string aurl_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Aurl {
          get { return aurl_; }
          set {
            aurl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ConnectPeer);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ConnectPeer other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Aurl != other.Aurl) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Aurl.Length != 0) hash ^= Aurl.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Aurl.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Aurl);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Aurl.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Aurl);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Aurl.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Aurl);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ConnectPeer other) {
          if (other == null) {
            return;
          }
          if (other.Aurl.Length != 0) {
            Aurl = other.Aurl;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Aurl = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Aurl = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class ConsoleInput : pb::IMessage<ConsoleInput>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ConsoleInput> _parser = new pb::MessageParser<ConsoleInput>(() => new ConsoleInput());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ConsoleInput> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::AbyssCLI.ABI.UIAction.Descriptor.NestedTypes[6]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ConsoleInput() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ConsoleInput(ConsoleInput other) : this() {
          elementId_ = other.elementId_;
          text_ = other.text_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ConsoleInput Clone() {
          return new ConsoleInput(this);
        }

        /// <summary>Field number for the "element_id" field.</summary>
        public const int ElementIdFieldNumber = 1;
        private int elementId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ElementId {
          get { return elementId_; }
          set {
            elementId_ = value;
          }
        }

        /// <summary>Field number for the "text" field.</summary>
        public const int TextFieldNumber = 2;
        private string text_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Text {
          get { return text_; }
          set {
            text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ConsoleInput);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ConsoleInput other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ElementId != other.ElementId) return false;
          if (Text != other.Text) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ElementId != 0) hash ^= ElementId.GetHashCode();
          if (Text.Length != 0) hash ^= Text.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ElementId != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ElementId);
          }
          if (Text.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Text);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ElementId != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ElementId);
          }
          if (Text.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Text);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ElementId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ElementId);
          }
          if (Text.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ConsoleInput other) {
          if (other == null) {
            return;
          }
          if (other.ElementId != 0) {
            ElementId = other.ElementId;
          }
          if (other.Text.Length != 0) {
            Text = other.Text;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ElementId = input.ReadInt32();
                break;
              }
              case 18: {
                Text = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ElementId = input.ReadInt32();
                break;
              }
              case 18: {
                Text = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
